# Project: AllegroBase
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = allegrobasemain.o $(RES)
LINKOBJ  = allegrobasemain.o $(RES)
LIBS =  -L"lib" -mwindows ../../../../Desktop/UtterCore/Dev-Cpp/lib/liballeg.a  -g3 
INCS =  -I"include"  -I"C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy" 
BIN  = AllegroBase.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before AllegroBase.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "AllegroBase.exe" $(LIBS)

allegrobasemain.o: allegrobasemain.cpp   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/SETUP.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/declarations.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/config.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/worldfuncs.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/player.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/actors.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/weapons.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/objectstruct.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/objects.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/animations.h   C:/Users/Utter/Documents/GitHub/UCrpg/Rpgthingy/loadsave.h
	$(CPP) -c allegrobasemain.cpp -o allegrobasemain.o $(CXXFLAGS)
